# https://dev.classmethod.jp/articles/docker-compose-yml-dir/
# なぜルート直下に置くのか

version: '3.8'

# docker-composeではサービスという単位でコンテナを管理
services:
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - "5403:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
  backend-server:
    links:
      - postgres
    depends_on:
      - postgres
    container_name: backend-server
    tty: true
    ports:
      - '3000:3000'
    build:
      # https://qiita.com/sam8helloworld/items/e7fffa9afc82aea68a7a
        context: . # 基準
        dockerfile: ../.docker/postgres/Dockerfile # contextからの相対パス
    volumes:
      - type: bind
        source: .
        target: /backend-server

volumes:
  postgres:
    driver: local
