 @startuml

 rectangle 参加者集約 {

   Object 参加者 {
     <集約ルート>
     ..
     参加者ID
     ..
     名前
     メールアドレス
     在籍ステータス
   }

   Object 在籍ステータス {
     在籍ステータス
     ..
     参加者ID
   }

 参加者 -- 在籍ステータス
 }

 rectangle ペア集約 {
   Object ペア {
     <集約ルート>
     ..
     ペアID
     ..
     参加者ID
     ペア名
   }
 }
 rectangle チーム集約 {
   Object チーム {
     <集約ルート>
     ..
     チームID
     ..
     ペアID
     チーム名
   }
 }
 rectangle 課題保有集約 {
  Object 参加者が保有する課題 {
     <集約ルート>
     ..
     参加者が保有する課題ID
     ..
     課題ID
     参加者ID
     進捗ステータス
   }

   Object 進捗ステータス {
     進捗ステータス
   }
  参加者が保有する課題 -- 進捗ステータス
 }

 rectangle 課題集約 {
   Object 課題 {
   <集約ルート>
     ..
     課題ID
     ..
     課題名
     ナンバー
     内容
   }
 }

  rectangle 課題グループ集約 {
    Object 課題グループ {
      グループ名
    }
   課題 -- 課題グループ
  }

  参加者 -- ペア
  ペア -- チーム
  参加者 -- 参加者が保有する課題
  参加者が保有する課題 -- 課題
	@enduml
